app:
  name: pipeFree
  version: 1.0.0
  description: A simple application to demonstrate configuration management.
  deployment:
    mode: dev
    debug: true

http:
  port: 8080

database:
  type: mysql
  host: localhost
  port: 3306
  password: password

redis:
  host: localhost
  port: 6379
  password: password

etcd:
  endpoints:
    - http://localhost:2379
  time:
    autoSyncInterval: 30 # second
    dialTimeout: 30 # second
    keepAlivePeriod: 30 # second
  retryCfg:
    maxSize: 5
    interval: 30 # second
    jitter: 0.3 # float

orca:
  dispatcher:
    queueSize: 1000