app:
  name: pipeFree
  version: 1.0.0
  description: A simple application to demonstrate configuration management.
  deployment:
    mode: dev
    debug: true


log:
  level: debug
  format: json
  appender:
    defaultAppender: stdout
    kafkaAppender:
      enabled: false
      topic: pipeFree
      brokers:
            - localhost:9092

http:
  port: 8080

mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  database: pipeFree
  migrate: true



etcd:
  endpoints:
    - http://127.0.0.1:2379
  timeout: 30 # seconds
  auth:
    username:
    password: 

