app:
  name: pipeFree
  version: 1.0.0
  description: A simple application to demonstrate configuration management.
  deployment:
    mode: dev
    debug: true


log:
  level: debug
  format: json
  appender:
    defaultAppender: stdout
    kafkaAppender:
      enabled: false
      topic: pipeFree
      brokers:
            - localhost:9092

http:
  port: 8080




etcd:
  endpoints:
    - http://localhost:2379
  time:
    autoSyncInterval: 30 # second
    dialTimeout: 30 # second
    keepAlivePeriod: 30 # second
  retryCfg:
    maxSize: 5
    interval: 30 # second
    jitter: 0.3 # float

nebula:
  address:
    - localhost:62186
  username: root
  password: <none>
  spaces:
    - test
    - pipe_exec
  sessionConfig:
    maxConnSize: 100
    minConnSize: 30
    idleTime: 30 # second
    timeout: 0 # second
    useHttp2: false

mongoDB:
    uri: mongodb://localhost:27017
    username: root
    password: <none>
    database: pipeFree
    collections:
      - pipe_cfg
      - pipe_exec_snapshot
    options:
      timeout: 30 # seconds
      maxPoolSize: 100
      minPoolSize: 10
      maxConnIdleTime: 30 # seconds
      needAuth: false

orca:
  watcher:
    queueSize: 1000