app:
  name: pipeFree
  version: 1.0.0
  description: A simple application to demonstrate configuration management.
  deployment:
    mode: dev
    debug: true


log:
  level: debug
  format: json
  appender:
    defaultAppender: stdout
    kafkaAppender:
      enabled: false
      topic: pipeFree
      brokers:
            - localhost:9092

http:
  port: 8080

mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  database: pipeFree
  migrate: true



etcd:
  endpoints:
    - http://localhost:2379
  time:
    autoSyncInterval: 30 # second
    dialTimeout: 30 # second
    keepAlivePeriod: 30 # second
  retryCfg:
    maxSize: 5
    interval: 30 # second
    jitter: 0.3 # float

