apiVersion: v1
kind: compound
metadata:
  name: NodeA
  operation: pipeLaunch
  namespace: default
  desc: Root node of the topology
spec:
  rawMessage: '{"type": "simple", "timeout": "30s"}'
env:
  keyValues:
    max_retry: 3
    log_level: debug
graph: # NodeA contains a subgraph
  edges:
    - from: NodeA
      to: NodeB
    - from: NodeA
      to: NodeC
    - from: NodeB
      to: NodeD
    - from: NodeC